FINNHUB_API_KEY: "cvs3atpr01qvc2muh4t0cvs3atpr01qvc2muh4tg"

FINNHUB_TICKERS:
  - AAPL
  - MSFT
  - TSLA
  - AMZN
  - GOOG

EMBEDDING_MODEL: "BAAI/bge-base-en-v1.5"

QDRANT:
  host: "localhost"
  port: 6333
  collection_name: "financial_news"

SCHEDULE_HOURS: 3
